### ISSUE TITLE
Support for docker

### ISSUE THREAD

**Issue by kicaj** [ishanvyas22/cakephp-jwt-authentication-demo#1]
Any possible to add docker support for this project?

**Comment by ishanvyas22** [comment]
This is plain simple CakePHP project which work with docker. So I don't actually understand what support do you need? What is the use case?

**Comment by kicaj** [comment]
I mean files `Dockerfile` and `docker-compose.yaml` inside the project repo.

**Comment by ishanvyas22** [comment]
I don't think there's need of it in this project. It should only exists if there's multiple persons working on same project and there's issues due to version or environment mismatch.

If you want to use docker to run this project feel free to create a docker files according to your needs.
